name: Triggered by Another Repo

on:
  repository_dispatch:
    types: [access-file]

jobs:
  access-file-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Use the file
        run: cat path/to/file.txt
